### ISSUE TITLE
Trubles creating the environment

### ISSUE THREAD

**Issue by mmazzolini** [marysa/ACDC2022#1]
Hi, 

I am trying to clone your environment.yml on a linux platform. I just run the following code 
```
conda env create -f environment.yml
```
but it seems anaconda fails to solve the environment.
```
ResolvePackageNotFound: 
  - libgfortran=5.0.0
  - llvm-openmp=12.0.0
  - appnope=0.1.2
  - python.app=3
```

am I doing something wrong or missing some software dependencies?

thanks a lot for your help,

Marco.

PS: I also tried with environment_nc.yml but looks like there are even more libraries not resolved.

**Comment by marysa** [comment]
I made the environment on a mac - but I've tried cloning environments from linux servers to my mac before and hit similar issues. I'll put a similar environment.yml file from a linux machine into the git repo shortly which may or may not work for you, or you can create your own environment from scratch - the main packages you'll want to try to include are:

- cartopy
- netcdf4
- xarray
- scipy
- scikit-learn
- cftime
- dask
- esmf
- esmpy
- xesmf
- ipython
- jupyter
- matplotlib
- numpy
- pandas

To do this, run 
`conda create --name acdc2022`

Then activate the environment:
`conda activate acdc2022`
and for each of the above (a bunch are dependent on each other so you won't actually have to install each one) run something like:
`conda install -c anaconda xarray` 
(packages come from different "channels", but a quick google of "conda package-you-want" will turn up the right line - e.g. cartopy, which plots maps, comes from the conda-forge channel: `conda install -c conda-forge cartopy` ).

**Comment by mmazzolini** [comment]
Thanks a lot for the quick response, I'll try with your new .yml, otherwise I'll do one from scratch. see you soon in Otta!

**Comment by marysa** [comment]
There is now a file called linux_environment.yml that might work. Good luck!

**Comment by mmazzolini** [comment]
> There is now a file called linux_environment.yml that might work. Good luck!

that file works for me! thanks a lot!
